title: "Hello"

sort:
  direction: desc
  by: filename

nav:
    - 主页: index.md
    - 技术: tech
    - 博客: blog
    - 记录: note
    - 专题: topic
    - 留言: message
    - 关于: readme
    - 链接: flinks
    - RSS: feed_rss_created.xml